import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    flex: 1,
  },
  timerContainer: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  timerText: {
    fontFamily: 'RujisHandwritingFontv.2.0',
    color: '#000',
    fontSize: 20,
  },
  progressContainer: {
    alignItems: 'center',
    flex: 2,
    justifyContent: 'center',
  },
  progressText: {
    fontFamily: 'RujisHandwritingFontv.2.0',
    color: '#227711',
    fontSize: 30,
    textAlign: 'center',
  },
  progressTextSmall: {
    fontFamily: 'RujisHandwritingFontv.2.0',
    color: '#000',
    fontSize: 16,
    textAlign: 'center',
  },
  resultContainer: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  resultText: {
    fontFamily: 'RujisHandwritingFontv.2.0',
    fontSize: 20,
    color: '#444',
  },
  columnContainer: {
    overflow: 'visible',
    flex: 1,
    flexDirection: 'row',
    maxWidth: 315,
  },
  leftColumn: {
    marginLeft: 5,
    flex: 4,
  },
  leftPapers: {
    position: 'absolute',
    height: 600,
    right: -20,
    top: -5,
    width: 300,
  },
  wordCount: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    position: 'absolute',
    left: 0,
    bottom: 5,
    right: 0,
  },
  wordCountText: {
    fontFamily: 'RujisHandwritingFontv.2.0',
    fontSize: 15,
    color: '#444',
    margin: 5,
  },
  wordWrapper: {
    flex: 1,
  },
  bluePaper: {
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    width: 500,
    height: 400,
    position: 'absolute',
    right: -15,
    bottom: -354,
  },
  rightColumn: {
    flex: 6,
    marginBottom: 10,
    marginLeft: 10,
    marginTop: 10,
  },
  listContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'visible',
  },
  rowWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 25,
    width: '100%',
  },
  rowEndImage: {
    alignItems: 'center',
    justifyContent: 'center',
    width: null,
    height: 5000,
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  rowStartImage: {
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    width: null,
    height: 5,
    marginTop: 30,
  },
  rowWrapperImage: {
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    flex: 1,
    width: null,
    height: null,
  },
  correct: {
    fontFamily: 'RujisHandwritingFontv.2.0',
    color: '#505050',
    fontSize: 20,
  },
  incorrect: {
    fontFamily: 'RujisHandwritingFontv.2.0',
    color: '#a3a3a3',
    fontSize: 20,
    textDecorationLine: 'line-through',
  },
  neutral: {
    fontFamily: 'RujisHandwritingFontv.2.0',
    color: '#444',
    fontSize: 20,
  },
});
