import { StyleSheet } from 'react-native';
import { verticalScale } from 'react-native-size-matters';

export default StyleSheet.create({
  container: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    flex: 1,
  },
  buttonWrapper: {
    height: verticalScale(35),
    justifyContent: 'center',
  },
  lineWrapperSmall: {
    alignItems: 'center',
    height: verticalScale(30),
    justifyContent: 'center',
    marginLeft: verticalScale(6),
  },
  lineWrapperLarge: {
    alignItems: 'center',
    height: verticalScale(60),
    justifyContent: 'center',
    marginLeft: verticalScale(6),
  },
  timerText: {
    fontFamily: 'RujisHandwritingFontv.2.0',
    color: '#000',
    fontSize: verticalScale(20),
  },
  starRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
  },
  starWrapper: {
    height: verticalScale(55),
    width: verticalScale(55),
  },
  star: {
    ...StyleSheet.absoluteFillObject,
    height: null,
    width: null,
  },
  resultContainer: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingLeft: verticalScale(10),
    paddingRight: verticalScale(10),
    paddingBottom: verticalScale(4),
  },
  resultText: {
    color: '#444',
    fontFamily: 'RujisHandwritingFontv.2.0',
    fontSize: verticalScale(20),
    textAlign: 'center',
  },
  resultTextFaded: {
    color: '#888',
    fontFamily: 'RujisHandwritingFontv.2.0',
    fontSize: verticalScale(20),
    textAlign: 'center',
  },
  columnContainer: {
    overflow: 'visible',
    flex: 1,
    flexDirection: 'row',
    maxWidth: verticalScale(315),
  },
  leftColumn: {
    marginLeft: verticalScale(5),
    flex: 4,
  },
  leftPapers: {
    position: 'absolute',
    height: verticalScale(600),
    right: verticalScale(-20),
    top: verticalScale(-5),
    width: verticalScale(300),
  },
  wordCount: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    position: 'absolute',
    left: 0,
    bottom: verticalScale(5),
    right: 0,
  },
  wordCountText: {
    fontFamily: 'RujisHandwritingFontv.2.0',
    fontSize: verticalScale(15),
    color: '#444',
    margin: verticalScale(5),
  },
  wordWrapper: {
    flex: 1,
  },
  bluePaper: {
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    width: verticalScale(500),
    height: verticalScale(400),
    position: 'absolute',
    right: verticalScale(-15),
    bottom: verticalScale(-354),
  },
  rightColumn: {
    flex: 6,
    justifyContent: 'space-between',
    marginBottom: verticalScale(10),
    marginLeft: verticalScale(10),
    marginTop: verticalScale(10),
  },
  listContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'visible',
  },
  rowWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    height: verticalScale(25),
    width: '100%',
  },
  rowEndImage: {
    alignItems: 'center',
    justifyContent: 'center',
    width: null,
    height: verticalScale(5000),
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  rowStartImage: {
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    width: null,
    height: verticalScale(5),
    marginTop: verticalScale(30),
  },
  rowWrapperImage: {
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    flex: 1,
    width: null,
    height: null,
  },
  correct: {
    fontFamily: 'RujisHandwritingFontv.2.0',
    color: '#505050',
    fontSize: verticalScale(20),
  },
  incorrect: {
    fontFamily: 'RujisHandwritingFontv.2.0',
    color: '#a3a3a3',
    fontSize: verticalScale(20),
    textDecorationLine: 'line-through',
  },
  neutral: {
    fontFamily: 'RujisHandwritingFontv.2.0',
    color: '#444',
    fontSize: verticalScale(20),
  },
});
